### PR TITLE
Split source_root directory creation and django project start command

### LINKED ISSUE #3: Setup fails when source_root is set to .
In [`pre_gen_project.sh`](https://github.com/dolphinkiss/cookiecutter-django-aws-eb/blob/master/hooks/pre_gen_project.sh#L24), creation of the `source_root` folder and the Django `startproject` command are chained with &&.

When the `source_root` setting is `.` (the default), `mkdir ./` fails and the `startproject` command is not executed. This causes project provisioning to fail with the following errors:

```bash
aws_eb_type [python/docker]: docker
project_name [myproject]: test 
django_version [1.9.1]: 1.11.8
setup_local_env [yes]: yes
virtualenv_bin [virtualenv]: 
source_root [.]: ./
---> Running pre-hook script...
New python executable in /Users/jaydenwindle/Documents/ScratchPad/test/.ve/bin/python2.7
Also creating executable in /Users/jaydenwindle/Documents/ScratchPad/test/.ve/bin/python
Installing setuptools, pip, wheel...done.
mkdir: ./: File exists
---> DONE Running pre-hook script...
---> Running post-hook script...
mv: rename .//test/settings.py to .//test/settings/common.py: No such file or directory
/var/folders/6j/bm6whsq12n71rlf831qtnz5c0000gn/T/tmpsZC79L.sh: line 26: .//test/settings/common.py: No such file or directory
sed: .//manage.py: No such file or directory
---> Created postgres database 'test'
---> DONE Running post-hook script...
```

### PR DESCRIPTION
**Pull request by jaydenwindle**
This PR fixes #3 by splitting the `source_root` directory creation from the Django `startproject` command. Now if the `source_root` directory creation fails the `startproject` command will still run.

### CODE REVIEW

File: hooks/pre_gen_project.sh [hunk 1]
```diff
@@ -21,6 +21,7 @@ fi
 
 {{ cookiecutter.virtualenv_bin }} .ve
 .ve/bin/pip install -q "django=={{ cookiecutter.django_version }}"
-mkdir "$source_root" && .ve/bin/django-admin.py startproject -v 0 "{{ cookiecutter.project_name }}" "{{ cookiecutter.source_root }}"
+mkdir "$source_root"
+.ve/bin/django-admin.py startproject -v 0 "{{ cookiecutter.project_name }}" "{{ cookiecutter.source_root }}"
```
Comment (peterlauri) [inline hooks/pre_gen_project.sh:25]: I think mkdir -p would be a better approach. But this is ok for now :)

**Review by peterlauri — APPROVED** [review]

**Comment by peterlauri** [comment]
Thanks for the PR! :)
